openapi: 3.0.1
info:
  title: statusOfApiByCountry
  description: API Definition of statusOfApiByCountry
  version: 1.0.0
servers:
- url: http://localhost:8290/api/v1/status
paths:
  /{country}:
    get:
      parameters:
      - name: country
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
